In [2]:
import boto3
import pandas as pd
import glob
import os
import json
import xmltodict
import sys
from collections import Counter
import numpy as np
from spellchecker import SpellChecker
from nltk.stem.wordnet import WordNetLemmatizer

In [3]:
fn = glob.glob(os.path.join('.', '*final.json'))[0]
fr = glob.glob(os.path.join('results3', '*final.json'))[0]

In [4]:
fn

'./created_2019-Jan-29_18_22_44_final.json'

In [5]:
fr

'results3/created_2019-Jan-29_18_22_44_final.json'

In [6]:
with open(fn, 'r') as handle:
    hitlist_a = json.load(handle)
with open(fr, 'r') as handle:
    resultlist_a = json.load(handle)
print(len(resultlist_a))
print(len(hitlist_a))
#print(hitlist_a)

4
4

In [7]:
fn = glob.glob(os.path.join('../../pilot01b2019/production', '*final.json'))[0]
fr = glob.glob(os.path.join('../../pilot01b2019/production/results3', '*final.json'))[0]
print(fn)
with open(fn, 'r') as handle:
    hitlist_b = json.load(handle)
with open(fr, 'r') as handle:
    resultlist_b = json.load(handle)
    

print(len(resultlist_b))
print(len(hitlist_b))
print(hitlist_b)

../../pilot01b2019/production/created_2019-Jan-29_15_02_20_final.json
4
4
[{'HIT': {'HITId': '30OITAWPBR8WKT016VTE67ZRJKBH9Z', 'HITTypeId': '3BIS89HFPL0BA9JSSFVWQLC6XEO1R0', 'HITGroupId': '3NVVDJT9H7SF36EZATH7618OHCHXPH', 'HITLayoutId': '3Z1ISOOYTVR8DK77D9EQ04V36BSOT2', 'Title': 'Name objects in images', 'Description': 'Look at an image and write down a name for the object in the red box', 'HITStatus': 'Assignable', 'MaxAssignments': 40, 'Reward': '0.15', 'AutoApprovalDelayInSeconds': 2592000, 'AssignmentDurationInSeconds': 900, 'QualificationRequirements': [{'QualificationTypeId': '00000000000000000040', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [2000], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '000000000000000000L0', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [80], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}], 'HITReviewStatus': 'NotReviewed', 'NumberOfAssignmentsPending': 0, 'NumberOfAssignmentsAvailable': 40, 'NumberOfAssignmentsCompleted': 0, 'params': [{'Name': 'img_0_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2389064_507067_ambiguous_synset.png'}, {'Name': 'img_1_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2316226_1055203_ambiguous_synset.png'}, {'Name': 'img_2_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2398812_1175558_ambiguous_synset.png'}, {'Name': 'img_3_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2403052_383993_ambiguous_synset.png'}, {'Name': 'img_4_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2393917_1215702_singleton_category.png'}, {'Name': 'img_5_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2363125_2056940_singleton_category.png'}, {'Name': 'img_6_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2356851_3120857_singleton_obj.png'}, {'Name': 'img_7_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2405320_654642_ambiguous_category.png'}, {'Name': 'img_8_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2393669_1217850_ambiguous_category.png'}, {'Name': 'img_9_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2330865_2895016_singleton_category.png'}]}, 'ResponseMetadata': {'RequestId': '16dd6244-07c6-4f5b-93f1-846467d267c4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '16dd6244-07c6-4f5b-93f1-846467d267c4', 'content-type': 'application/x-amz-json-1.1', 'content-length': '26933', 'date': 'Tue, 29 Jan 2019 14:02:20 GMT'}, 'RetryAttempts': 0}, 'Images': {'0': ['2389064', '507067', 'ambiguous_synset', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2389064_507067_ambiguous_synset.png'], '1': ['2316226', '1055203', 'ambiguous_synset', 'aircraft.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2316226_1055203_ambiguous_synset.png'], '2': ['2398812', '1175558', 'ambiguous_synset', 'horse.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2398812_1175558_ambiguous_synset.png'], '3': ['2403052', '383993', 'ambiguous_synset', 'ungulate.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2403052_383993_ambiguous_synset.png'], '4': ['2393917', '1215702', 'singleton_category', 'flower.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2393917_1215702_singleton_category.png'], '5': ['2363125', '2056940', 'singleton_category', 'overgarment.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2363125_2056940_singleton_category.png'], '6': ['2356851', '3120857', 'singleton_obj', 'flower.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2356851_3120857_singleton_obj.png'], '7': ['2405320', '654642', 'ambiguous_category', 'overgarment.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2405320_654642_ambiguous_category.png'], '8': ['2393669', '1217850', 'ambiguous_category', 'car.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2393669_1217850_ambiguous_category.png'], '9': ['2330865', '2895016', 'singleton_category', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2330865_2895016_singleton_category.png']}}, {'HIT': {'HITId': '3538U0YQ1GZQRVKFUW44C9KS3DOF3I', 'HITTypeId': '3BIS89HFPL0BA9JSSFVWQLC6XEO1R0', 'HITGroupId': '3NVVDJT9H7SF36EZATH7618OHCHXPH', 'HITLayoutId': '3Z1ISOOYTVR8DK77D9EQ04V36BSOT2', 'Title': 'Name objects in images', 'Description': 'Look at an image and write down a name for the object in the red box', 'HITStatus': 'Assignable', 'MaxAssignments': 40, 'Reward': '0.15', 'AutoApprovalDelayInSeconds': 2592000, 'AssignmentDurationInSeconds': 900, 'QualificationRequirements': [{'QualificationTypeId': '00000000000000000040', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [2000], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '000000000000000000L0', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [80], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}], 'HITReviewStatus': 'NotReviewed', 'NumberOfAssignmentsPending': 0, 'NumberOfAssignmentsAvailable': 40, 'NumberOfAssignmentsCompleted': 0, 'params': [{'Name': 'img_0_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2417401_2805653_ambiguous_synset.png'}, {'Name': 'img_1_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2362871_2391867_ambiguous_category.png'}, {'Name': 'img_2_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2385325_1298357_singleton_category.png'}, {'Name': 'img_3_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2403323_354473_singleton_obj.png'}, {'Name': 'img_4_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2367161_2481329_ambiguous_synset.png'}, {'Name': 'img_5_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2408164_266906_singleton_category.png'}, {'Name': 'img_6_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/4070_1556532_ambiguous_synset.png'}, {'Name': 'img_7_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2384721_1305893_singleton_category.png'}, {'Name': 'img_8_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2327756_2739137_singleton_obj.png'}, {'Name': 'img_9_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2373806_1986195_ambiguous_synset.png'}]}, 'ResponseMetadata': {'RequestId': 'dfe5d677-9794-47c5-ada0-353462779125', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'dfe5d677-9794-47c5-ada0-353462779125', 'content-type': 'application/x-amz-json-1.1', 'content-length': '26926', 'date': 'Tue, 29 Jan 2019 14:02:21 GMT'}, 'RetryAttempts': 0}, 'Images': {'0': ['2417401', '2805653', 'ambiguous_synset', 'ungulate.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2417401_2805653_ambiguous_synset.png'], '1': ['2362871', '2391867', 'ambiguous_category', 'ship.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2362871_2391867_ambiguous_category.png'], '2': ['2385325', '1298357', 'singleton_category', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2385325_1298357_singleton_category.png'], '3': ['2403323', '354473', 'singleton_obj', 'horse.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2403323_354473_singleton_obj.png'], '4': ['2367161', '2481329', 'ambiguous_synset', 'neckwear.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2367161_2481329_ambiguous_synset.png'], '5': ['2408164', '266906', 'singleton_category', 'bird.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2408164_266906_singleton_category.png'], '6': ['4070', '1556532', 'ambiguous_synset', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/4070_1556532_ambiguous_synset.png'], '7': ['2384721', '1305893', 'singleton_category', 'overgarment.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2384721_1305893_singleton_category.png'], '8': ['2327756', '2739137', 'singleton_obj', 'headdress.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2327756_2739137_singleton_obj.png'], '9': ['2373806', '1986195', 'ambiguous_synset', 'car.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2373806_1986195_ambiguous_synset.png']}}, {'HIT': {'HITId': '3CVBMEMMXCLS6AC8RYVUSB8LOUO7HE', 'HITTypeId': '3BIS89HFPL0BA9JSSFVWQLC6XEO1R0', 'HITGroupId': '3NVVDJT9H7SF36EZATH7618OHCHXPH', 'HITLayoutId': '3Z1ISOOYTVR8DK77D9EQ04V36BSOT2', 'Title': 'Name objects in images', 'Description': 'Look at an image and write down a name for the object in the red box', 'HITStatus': 'Assignable', 'MaxAssignments': 40, 'Reward': '0.15', 'AutoApprovalDelayInSeconds': 2592000, 'AssignmentDurationInSeconds': 900, 'QualificationRequirements': [{'QualificationTypeId': '00000000000000000040', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [2000], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '000000000000000000L0', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [80], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}], 'HITReviewStatus': 'NotReviewed', 'NumberOfAssignmentsPending': 0, 'NumberOfAssignmentsAvailable': 40, 'NumberOfAssignmentsCompleted': 0, 'params': [{'Name': 'img_0_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2365594_2254805_singleton_category.png'}, {'Name': 'img_1_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2316079_3206535_ambiguous_synset.png'}, {'Name': 'img_2_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2417043_3198072_ambiguous_category.png'}, {'Name': 'img_3_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2370234_1757900_singleton_category.png'}, {'Name': 'img_4_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2397143_436817_singleton_obj.png'}, {'Name': 'img_5_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2370214_605402_singleton_category.png'}, {'Name': 'img_6_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2390817_1246716_singleton_category.png'}, {'Name': 'img_7_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2319108_1004620_ambiguous_synset.png'}, {'Name': 'img_8_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2333895_3489083_singleton_category.png'}, {'Name': 'img_9_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2343599_921837_ambiguous_category.png'}]}, 'ResponseMetadata': {'RequestId': '5c3dd19b-507d-4efb-9b22-ec281492804f', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '5c3dd19b-507d-4efb-9b22-ec281492804f', 'content-type': 'application/x-amz-json-1.1', 'content-length': '26937', 'date': 'Tue, 29 Jan 2019 14:12:23 GMT'}, 'RetryAttempts': 0}, 'Images': {'0': ['2365594', '2254805', 'singleton_category', 'aircraft.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2365594_2254805_singleton_category.png'], '1': ['2316079', '3206535', 'ambiguous_synset', 'neckwear.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2316079_3206535_ambiguous_synset.png'], '2': ['2417043', '3198072', 'ambiguous_category', 'car.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2417043_3198072_ambiguous_category.png'], '3': ['2370234', '1757900', 'singleton_category', 'bird.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2370234_1757900_singleton_category.png'], '4': ['2397143', '436817', 'singleton_obj', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2397143_436817_singleton_obj.png'], '5': ['2370214', '605402', 'singleton_category', 'overgarment.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2370214_605402_singleton_category.png'], '6': ['2390817', '1246716', 'singleton_category', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2390817_1246716_singleton_category.png'], '7': ['2319108', '1004620', 'ambiguous_synset', 'ungulate.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2319108_1004620_ambiguous_synset.png'], '8': ['2333895', '3489083', 'singleton_category', 'ungulate.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2333895_3489083_singleton_category.png'], '9': ['2343599', '921837', 'ambiguous_category', 'headdress.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2343599_921837_ambiguous_category.png']}}, {'HIT': {'HITId': '3D4BBDG7ZI1JOJ053UE343ZP60XC35', 'HITTypeId': '3BIS89HFPL0BA9JSSFVWQLC6XEO1R0', 'HITGroupId': '3NVVDJT9H7SF36EZATH7618OHCHXPH', 'HITLayoutId': '3Z1ISOOYTVR8DK77D9EQ04V36BSOT2', 'Title': 'Name objects in images', 'Description': 'Look at an image and write down a name for the object in the red box', 'HITStatus': 'Assignable', 'MaxAssignments': 40, 'Reward': '0.15', 'AutoApprovalDelayInSeconds': 2592000, 'AssignmentDurationInSeconds': 900, 'QualificationRequirements': [{'QualificationTypeId': '00000000000000000040', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [2000], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '000000000000000000L0', 'Comparator': 'GreaterThanOrEqualTo', 'IntegerValues': [80], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}, {'QualificationTypeId': '00000000000000000071', 'Comparator': 'In', 'LocaleValues': [{'Country': 'AU'}, {'Country': 'CA'}, {'Country': 'GB'}, {'Country': 'IE'}, {'Country': 'NZ'}, {'Country': 'US'}], 'RequiredToPreview': True, 'ActionsGuarded': 'PreviewAndAccept'}], 'HITReviewStatus': 'NotReviewed', 'NumberOfAssignmentsPending': 0, 'NumberOfAssignmentsAvailable': 40, 'NumberOfAssignmentsCompleted': 0, 'params': [{'Name': 'img_0_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2391964_484515_ambiguous_synset.png'}, {'Name': 'img_1_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2349445_874713_singleton_category.png'}, {'Name': 'img_2_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2350885_864652_singleton_category.png'}, {'Name': 'img_3_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2356284_1694677_ambiguous_synset.png'}, {'Name': 'img_4_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2363673_763118_ambiguous_synset.png'}, {'Name': 'img_5_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2382025_1331957_singleton_obj.png'}, {'Name': 'img_6_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2346998_894511_singleton_obj.png'}, {'Name': 'img_7_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2379445_552755_ambiguous_synset.png'}, {'Name': 'img_8_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2341107_3656954_singleton_category.png'}, {'Name': 'img_9_url', 'Value': 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2349587_2162340_ambiguous_synset.png'}]}, 'ResponseMetadata': {'RequestId': 'cd6a4718-a7aa-430d-aba4-599babf30094', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'cd6a4718-a7aa-430d-aba4-599babf30094', 'content-type': 'application/x-amz-json-1.1', 'content-length': '26923', 'date': 'Tue, 29 Jan 2019 14:12:23 GMT'}, 'RetryAttempts': 0}, 'Images': {'0': ['2391964', '484515', 'ambiguous_synset', 'bird.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2391964_484515_ambiguous_synset.png'], '1': ['2349445', '874713', 'singleton_category', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2349445_874713_singleton_category.png'], '2': ['2350885', '864652', 'singleton_category', 'furnishing.n.02', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2350885_864652_singleton_category.png'], '3': ['2356284', '1694677', 'ambiguous_synset', 'boat.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2356284_1694677_ambiguous_synset.png'], '4': ['2363673', '763118', 'ambiguous_synset', 'bird.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2363673_763118_ambiguous_synset.png'], '5': ['2382025', '1331957', 'singleton_obj', 'aircraft.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2382025_1331957_singleton_obj.png'], '6': ['2346998', '894511', 'singleton_obj', 'train.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2346998_894511_singleton_obj.png'], '7': ['2379445', '552755', 'ambiguous_synset', 'ungulate.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2379445_552755_ambiguous_synset.png'], '8': ['2341107', '3656954', 'singleton_category', 'headdress.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2341107_3656954_singleton_category.png'], '9': ['2349587', '2162340', 'ambiguous_synset', 'bird.n.01', 'http://www.coli.uni-saarland.de/~carina/object_naming/amt_images/2349587_2162340_ambiguous_synset.png']}}]

In [8]:
hit2images = {}
for hit in hitlist_a + hitlist_b:
    hit2images[hit['HIT']['HITId']] = hit['Images']

In [9]:
hit2images.keys()

dict_keys(['36MUZ9VAE77W39MGSAQA70L4IPAED9', '368IUKXGA6D1FRWRR1Y7V6AGFAP6PU', '3L1EFR8WWUAC6X9VB55E3MNE35A9F5', '3CMV9YRYP46NC1W0JSZPNT61W68JLF', '30OITAWPBR8WKT016VTE67ZRJKBH9Z', '3538U0YQ1GZQRVKFUW44C9KS3DOF3I', '3CVBMEMMXCLS6AC8RYVUSB8LOUO7HE', '3D4BBDG7ZI1JOJ053UE343ZP60XC35'])

In [10]:
obj2answers = {}
obj2info = {}
for assignm in resultlist_a:
    hitid = assignm['HITId']
    print(hitid)
    for a in assignm['Assignments']:
        #print(a)
        answers = a['Answers']
        for ix in range(10):
            object_id = hit2images[hitid][str(ix)][1]
            name = answers[str(ix)]['inputbox_objname-'+str(ix)]
            if object_id not in obj2answers:
                obj2answers[object_id] = {'a':Counter(),\
                                          'b':Counter(),\
                                          't':Counter()}
                obj2info[object_id] = hit2images[hitid][str(ix)]
                
            if name:
                name = name.lower()
                obj2answers[object_id]['a'][name] += 1
                obj2answers[object_id]['t'][name] += 1
                
for assignm in resultlist_b:
    hitid = assignm['HITId']
    print(hitid)
    for a in assignm['Assignments']:
        #print(a)
        answers = a['Answers']
        for ix in range(10):
            object_id = hit2images[hitid][str(ix)][1]
            name = answers[str(ix)]['inputbox_objname-'+str(ix)]
                
            if name:
                name = name.lower()
                obj2answers[object_id]['b'][name] += 1
                obj2answers[object_id]['t'][name] += 1

36MUZ9VAE77W39MGSAQA70L4IPAED9
368IUKXGA6D1FRWRR1Y7V6AGFAP6PU
3L1EFR8WWUAC6X9VB55E3MNE35A9F5
3CMV9YRYP46NC1W0JSZPNT61W68JLF
30OITAWPBR8WKT016VTE67ZRJKBH9Z
3538U0YQ1GZQRVKFUW44C9KS3DOF3I
3CVBMEMMXCLS6AC8RYVUSB8LOUO7HE
3D4BBDG7ZI1JOJ053UE343ZP60XC35

In [11]:
allrows = []
for objid in obj2answers:
    row = obj2info[objid]
    row.append(obj2answers[objid]['a'])
    row.append(obj2answers[objid]['b'])
    row.append(obj2answers[objid]['t'])
    allrows.append(row)

In [12]:
fulldf = pd.DataFrame(allrows,columns=['vg_img_id','vg_object_id','cat','synset','url','responses_a','responses_b','responses_total'])

In [13]:
fulldf

,vg_img_id,vg_object_id,cat,synset,url,responses_a,responses_b,responses_total
0,2389064,507067,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'ottoman': 25, 'outtoman': 1, 'sofar': 1, 'po...","{'ottomon': 1, 'cushion': 2, 'ottoman': 23, 'o...","{'ottoman': 48, 'outtoman': 1, 'sofar': 1, 'po..."
1,2316226,1055203,ambiguous_synset,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jet fighter': 2, 'jet': 18, 'aircraft': 1, '...","{'airplane': 7, 'jet': 15, 'fighter jet': 8, '...","{'jet fighter': 3, 'jet': 33, 'aircraft': 1, '..."
2,2398812,1175558,ambiguous_synset,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse head': 6, 'horse': 28, 'horse's head':...","{'horse': 27, 'horse's head': 1, 'horse head':...","{'horse head': 12, 'horse': 55, 'horse's head'..."
3,2403052,383993,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby zebra': 1, 'zebra': 37, 'line horse': 1}","{'zebra': 36, 'baby zebra': 2, 'horse': 1, 'ch...","{'baby zebra': 3, 'zebra': 73, 'line horse': 1..."
4,2393917,1215702,singleton_category,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sunflower': 29, 'sun flower': 4, 'flower': 5...","{'sunflower': 30, 'sun flower': 2, 'tie': 1, '...","{'sunflower': 59, 'sun flower': 6, 'flower': 9..."
5,2363125,2056940,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'man': 1, 'coat': 2, 'shirt': 1...","{'jacket': 16, 'coat': 4, 'upper body of human...","{'jacket': 38, 'man': 2, 'coat': 6, 'shirt': 1..."
6,2356851,3120857,singleton_obj,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'dandelion': 6, 'flower': 26, 'marigold': 1, ...","{'flower': 27, 'flowers': 1, 'yellow flower': ...","{'dandelion': 11, 'flower': 53, 'marigold': 1,..."
7,2405320,654642,ambiguous_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'baby sling': 2, 'towel': 1, 'napki...","{'scarf': 2, 'body wrap': 2, 'carrier': 1, 'up...","{'man': 4, 'baby sling': 4, 'towel': 1, 'napki..."
8,2393669,1217850,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'car': 35, 'automobile': 1, 'vehicle': 2, 'ca...","{'car': 33, 'salon car': 1, 'automobile': 4, '...","{'car': 68, 'automobile': 5, 'vehicle': 3, 'ca..."
9,2330865,2895016,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'dirt bike': 1, 'mat': 15, 'floor mat': 4, 'c...","{'mat': 14, 'floor mat': 9, 'floor matt': 1, '...","{'dirt bike': 1, 'mat': 29, 'floor mat': 13, '..."
10,2417401,2805653,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bull': 16, 'cow': 12, 'oxen': 2, 'ox pulling...","{'cow': 16, 'animal': 3, 'bull': 9, 'bison': 1...","{'bull': 25, 'cow': 28, 'oxen': 4, 'ox pulling..."
11,2362871,2391867,ambiguous_category,ship.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'ferry': 4, 'ship': 16, 'boat': 13, 'yaht': 1...","{'ship': 16, 'boat': 16, 'ferry': 4, 'passenge...","{'ferry': 8, 'ship': 32, 'boat': 29, 'yaht': 1..."
12,2385325,1298357,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'sofa': 12, 'couch': 21, 'sofar': 1, 'settee'...","{'couch': 22, 'sofa': 14, 'small couch': 1, 'c...","{'sofa': 26, 'couch': 43, 'sofar': 2, 'settee'..."
13,2403323,354473,singleton_obj,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse': 35, 'clydsdale': 1, 'horus': 1, 'cly...","{'horse': 38, 'clydesdale': 1, 'draft horse': 1}","{'horse': 73, 'clydsdale': 1, 'horus': 1, 'cly..."
14,2367161,2481329,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 22, 'necktie': 5, 'fabric': 1, 'neck t...","{'tie': 20, 'ties': 5, 'necktie': 6, 'neck tie...","{'tie': 42, 'necktie': 11, 'fabric': 2, 'neck ..."
15,2408164,266906,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'penguin': 25, 'bird': 9, 'baby penguin': 1, ...","{'bird': 18, 'penguin': 20, 'penquin': 2}","{'penguin': 45, 'bird': 27, 'baby penguin': 1,..."
16,4070,1556532,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'carpet': 27, 'bed skirt': 1, 'floor': 4, 'ru...","{'carpet': 24, 'floor': 5, 'rug': 2, 'floor ca...","{'carpet': 51, 'bed skirt': 1, 'floor': 9, 'ru..."
17,2384721,1305893,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'rain jacket': 1, 'man': 4, 've...","{'person': 3, 'man': 3, 'windbreaker': 2, 'car...","{'jacket': 39, 'rain jacket': 1, 'man': 7, 've..."
18,2327756,2739137,singleton_obj,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'beanie': 4, 'face': 11, 'man': 6, 'touque': ...","{'head': 1, 'face': 13, 'beanie': 6, 'cap': 2,...","{'beanie': 10, 'face': 24, 'man': 10, 'touque'..."
19,2373806,1986195,ambiguous_synset,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'police officer': 4, 'police': 2, 'man': 1, '...","{'motorbike': 1, 'man': 3, 'man on scooter': 1...","{'police officer': 5, 'police': 3, 'man': 4, '..."
20,2365594,2254805,singleton_category,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby': 3, 'balloon': 12, 'newborn': 1, 'peop...","{'balloon': 17, 'baby': 2, 'man': 3, 'wall dec...","{'baby': 5, 'balloon': 29, 'newborn': 1, 'peop..."
21,2316079,3206535,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 1, 'bowtie': 12, 'bow tie': 8, 'bow': ...","{'bowtie': 15, 'bow': 8, 'bow tie': 8, 'knot':...","{'tie': 3, 'bowtie': 27, 'bow tie': 16, 'bow':..."
22,2417043,3198072,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'van': 16, 'bus': 14, 'minibus': 1, 'tour-bus...","{'van': 13, 'bus': 20, 'vehicle': 1, 'automobi...","{'van': 29, 'bus': 34, 'minibus': 1, 'tour-bus..."
23,2370234,1757900,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 31, 'bad': 1, 'bird with very long be...","{'bird': 32, 'swan': 1, 'black-headed ibis': 1...","{'bird': 63, 'bad': 1, 'bird with very long be..."
24,2397143,436817,singleton_obj,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'desk': 22, 'filing cabinet': 1, 'drawers': 1...","{'desk': 25, 'filing cabinet': 1, 'table': 6, ...","{'desk': 47, 'filing cabinet': 2, 'drawers': 1..."
25,2370214,605402,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'top': 1, 'pancho': 3, 'poncho': 19...","{'poncho': 19, 'top': 1, 'shirt': 3, 'parka': ...","{'man': 3, 'top': 2, 'pancho': 6, 'poncho': 38..."
26,2390817,1246716,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 3, 'curtain': 27, 'curtains': 1, 'wind...","{'curtain': 29, 'net curtain': 1, 'curtains': ...","{'cat': 6, 'curtain': 56, 'curtains': 2, 'wind..."
27,2319108,1004620,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'gizelle': 1, 'gazelle': 8, 'ram': 2, 'antelo...","{'gazelle': 6, 'antelope': 13, 'elk': 3, 'deer...","{'gizelle': 1, 'gazelle': 14, 'ram': 2, 'antel..."
28,2333895,3489083,singleton_category,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sheep': 32, 'lamb': 1}","{'sheep': 36, 'lamb': 2, 'ship': 1, 'goat': 1}","{'sheep': 68, 'lamb': 3, 'ship': 1, 'goat': 1}"
29,2343599,921837,ambiguous_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'helmet': 27, 'hat': 4, 'white helment': 1, '...","{'helmet': 27, 'hat': 5, 'cap': 1, 'hard hat':...","{'helmet': 54, 'hat': 9, 'white helment': 1, '..."
30,2391964,484515,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'flamingo': 36, 'crane': 1, 'pink flamingo': ...","{'flamingo': 34, 'bird': 4, 'cow': 1, 'pink fl...","{'flamingo': 70, 'crane': 1, 'pink flamingo': ..."
31,2349445,874713,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 12, 'bench': 12, 'washing line': 1, 'c...","{'bench': 11, 'cat': 10, 'ship': 1, 'tabby cat...","{'cat': 22, 'bench': 23, 'washing line': 2, 'c..."
32,2350885,864652,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 22, 'sofas': 1, 'couch': 4, 'picture':...","{'cat': 21, 'sofa': 5, 'calico cat': 1, 'art w...","{'cat': 43, 'sofas': 1, 'couch': 7, 'picture':..."
33,2356284,1694677,ambiguous_synset,boat.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'boat': 30, 'canoe': 1, 'rowboat': 3, 'row bo...","{'boat': 20, 'row boat': 4, 'humans in a boat'...","{'boat': 50, 'canoe': 6, 'rowboat': 7, 'row bo..."
34,2363673,763118,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 14, 'seagull': 14, 'birds': 1, 'pigeo...","{'seagull': 11, 'bird': 12, 'pigeon': 7, 'tie'...","{'bird': 26, 'seagull': 25, 'birds': 2, 'pigeo..."
35,2382025,1331957,singleton_obj,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'plane': 8, 'jet': 13, 'fighter jet': 7, 'air...","{'jet': 14, 'helecopter': 1, 'airplane': 3, 'f...","{'plane': 12, 'jet': 27, 'fighter jet': 18, 'a..."
36,2346998,894511,singleton_obj,train.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'train': 36, 'bus': 1, 'bullet train': 1, 'tr...","{'train': 36, 'floor': 1, 'high-speed train': ...","{'train': 72, 'bus': 1, 'bullet train': 1, 'tr..."
37,2379445,552755,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,{'zebra': 33},"{'zebra': 24, 'cheeta': 1, 'man': 1, 'ostrich'...","{'zebra': 57, 'cheeta': 1, 'man': 1, 'ostrich'..."
38,2341107,3656954,singleton_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'hat': 35, 'brim of a hat': 1, 'fisherman's h...","{'hat': 34, 'face': 1, 'hst': 1, 'fishing hat'...","{'hat': 69, 'brim of a hat': 1, 'fisherman's h..."
39,2349587,2162340,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'parrot': 31, 'tucan': 1, 'bird': 5, 'macaw': 2}","{'parrot': 25, 'bird': 5, 'macaw': 4, 'bike': ...","{'parrot': 56, 'tucan': 1, 'bird': 10, 'macaw'..."

In [14]:
def get_mae(row):
    a = []
    b = []
    for name in row['responses_total']:
        a.append(row['responses_a'][name])
        b.append(row['responses_b'][name])
        
    #print(a)
    #print(b)
    #r = spearmanr(np.array(a),np.array(b))
    #print(r[0])
    
    mean_abs_error = np.mean(np.abs((np.array(a) - np.array(b))))
    
    #print(mean_abs_error)
    return mean_abs_error

In [15]:
def get_agreement(rdict):
   
    vec = np.array([rdict[key] for key in rdict if rdict[key] > 1])
    vec_rel = vec/(np.sum(vec))
    #print(vec)
    #print(vec_rel)
    agr = np.sum(vec_rel * np.log2(1/vec_rel))
    
    return agr

In [16]:
get_agreement(fulldf.iloc[0]['responses_total'])

1.1489694603653073

In [17]:
fulldf['agr_total'] = fulldf['responses_total'].apply(lambda x: get_agreement(x))
fulldf['agr_a'] = fulldf['responses_a'].apply(lambda x: get_agreement(x))
fulldf['agr_b'] = fulldf['responses_b'].apply(lambda x: get_agreement(x))

In [18]:
fulldf['mae_a_b'] = [get_mae(row) for ix,row in fulldf.iterrows()]

In [19]:
fulldf

,vg_img_id,vg_object_id,cat,synset,url,responses_a,responses_b,responses_total,agr_total,agr_a,agr_b,mae_a_b
0,2389064,507067,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'ottoman': 25, 'outtoman': 1, 'sofar': 1, 'po...","{'ottomon': 1, 'cushion': 2, 'ottoman': 23, 'o...","{'ottoman': 48, 'outtoman': 1, 'sofar': 1, 'po...",1.148969,0.716726,0.850326,0.916667
1,2316226,1055203,ambiguous_synset,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jet fighter': 2, 'jet': 18, 'aircraft': 1, '...","{'airplane': 7, 'jet': 15, 'fighter jet': 8, '...","{'jet fighter': 3, 'jet': 33, 'aircraft': 1, '...",2.065899,1.794737,2.014719,1.294118
2,2398812,1175558,ambiguous_synset,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse head': 6, 'horse': 28, 'horse's head':...","{'horse': 27, 'horse's head': 1, 'horse head':...","{'horse head': 12, 'horse': 55, 'horse's head'...",1.212842,0.672295,1.040852,0.900000
3,2403052,383993,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby zebra': 1, 'zebra': 37, 'line horse': 1}","{'zebra': 36, 'baby zebra': 2, 'horse': 1, 'ch...","{'baby zebra': 3, 'zebra': 73, 'line horse': 1...",0.239874,0.000000,0.297472,1.000000
4,2393917,1215702,singleton_category,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sunflower': 29, 'sun flower': 4, 'flower': 5...","{'sunflower': 30, 'sun flower': 2, 'tie': 1, '...","{'sunflower': 59, 'sun flower': 6, 'flower': 9...",1.075361,1.024478,0.803072,1.000000
5,2363125,2056940,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'man': 1, 'coat': 2, 'shirt': 1...","{'jacket': 16, 'coat': 4, 'upper body of human...","{'jacket': 38, 'man': 2, 'coat': 6, 'shirt': 1...",1.443496,0.871096,1.251629,1.222222
6,2356851,3120857,singleton_obj,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'dandelion': 6, 'flower': 26, 'marigold': 1, ...","{'flower': 27, 'flowers': 1, 'yellow flower': ...","{'dandelion': 11, 'flower': 53, 'marigold': 1,...",0.896113,0.978016,0.625262,1.000000
7,2405320,654642,ambiguous_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'baby sling': 2, 'towel': 1, 'napki...","{'scarf': 2, 'body wrap': 2, 'carrier': 1, 'up...","{'man': 4, 'baby sling': 4, 'towel': 1, 'napki...",3.357052,3.083587,2.789866,1.093750
8,2393669,1217850,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'car': 35, 'automobile': 1, 'vehicle': 2, 'ca...","{'car': 33, 'salon car': 1, 'automobile': 4, '...","{'car': 68, 'automobile': 5, 'vehicle': 3, 'ca...",0.585927,0.303375,0.494183,1.500000
9,2330865,2895016,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'dirt bike': 1, 'mat': 15, 'floor mat': 4, 'c...","{'mat': 14, 'floor mat': 9, 'floor matt': 1, '...","{'dirt bike': 1, 'mat': 29, 'floor mat': 13, '...",2.216130,1.750632,1.954940,1.315789
10,2417401,2805653,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bull': 16, 'cow': 12, 'oxen': 2, 'ox pulling...","{'cow': 16, 'animal': 3, 'bull': 9, 'bison': 1...","{'bull': 25, 'cow': 28, 'oxen': 4, 'ox pulling...",1.961709,1.530639,1.597417,1.500000
11,2362871,2391867,ambiguous_category,ship.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'ferry': 4, 'ship': 16, 'boat': 13, 'yaht': 1...","{'ship': 16, 'boat': 16, 'ferry': 4, 'passenge...","{'ferry': 8, 'ship': 32, 'boat': 29, 'yaht': 1...",1.545783,1.404827,1.392147,0.909091
12,2385325,1298357,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'sofa': 12, 'couch': 21, 'sofar': 1, 'settee'...","{'couch': 22, 'sofa': 14, 'small couch': 1, 'c...","{'sofa': 26, 'couch': 43, 'sofar': 2, 'settee'...",1.113961,0.945660,0.964079,1.000000
13,2403323,354473,singleton_obj,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse': 35, 'clydsdale': 1, 'horus': 1, 'cly...","{'horse': 38, 'clydesdale': 1, 'draft horse': 1}","{'horse': 73, 'clydsdale': 1, 'horus': 1, 'cly...",0.000000,0.000000,0.000000,1.333333
14,2367161,2481329,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 22, 'necktie': 5, 'fabric': 1, 'neck t...","{'tie': 20, 'ties': 5, 'necktie': 6, 'neck tie...","{'tie': 42, 'necktie': 11, 'fabric': 2, 'neck ...",1.587083,1.360249,1.291036,1.250000
15,2408164,266906,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'penguin': 25, 'bird': 9, 'baby penguin': 1, ...","{'bird': 18, 'penguin': 20, 'penquin': 2}","{'penguin': 45, 'bird': 27, 'baby penguin': 1,...",1.158549,0.833765,1.234498,3.000000
16,4070,1556532,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'carpet': 27, 'bed skirt': 1, 'floor': 4, 'ru...","{'carpet': 24, 'floor': 5, 'rug': 2, 'floor ca...","{'carpet': 51, 'bed skirt': 1, 'floor': 9, 'ru...",0.856996,0.554778,0.965527,1.250000
17,2384721,1305893,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'rain jacket': 1, 'man': 4, 've...","{'person': 3, 'man': 3, 'windbreaker': 2, 'car...","{'jacket': 39, 'rain jacket': 1, 'man': 7, 've...",1.670151,0.619382,2.018821,1.562500
18,2327756,2739137,singleton_obj,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'beanie': 4, 'face': 11, 'man': 6, 'touque': ...","{'head': 1, 'face': 13, 'beanie': 6, 'cap': 2,...","{'beanie': 10, 'face': 24, 'man': 10, 'touque'...",2.180037,1.896687,2.079188,1.428571
19,2373806,1986195,ambiguous_synset,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'police officer': 4, 'police': 2, 'man': 1, '...","{'motorbike': 1, 'man': 3, 'man on scooter': 1...","{'police officer': 5, 'police': 3, 'man': 4, '...",3.131673,2.696620,2.458875,1.250000
20,2365594,2254805,singleton_category,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby': 3, 'balloon': 12, 'newborn': 1, 'peop...","{'balloon': 17, 'baby': 2, 'man': 3, 'wall dec...","{'baby': 5, 'balloon': 29, 'newborn': 1, 'peop...",1.024478,0.721928,0.993897,1.454545
21,2316079,3206535,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 1, 'bowtie': 12, 'bow tie': 8, 'bow': ...","{'bowtie': 15, 'bow': 8, 'bow tie': 8, 'knot':...","{'tie': 3, 'bowtie': 27, 'bow tie': 16, 'bow':...",1.889917,1.565596,1.969187,1.230769
22,2417043,3198072,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'van': 16, 'bus': 14, 'minibus': 1, 'tour-bus...","{'van': 13, 'bus': 20, 'vehicle': 1, 'automobi...","{'van': 29, 'bus': 34, 'minibus': 1, 'tour-bus...",1.520568,0.996792,1.465013,1.700000
23,2370234,1757900,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 31, 'bad': 1, 'bird with very long be...","{'bird': 32, 'swan': 1, 'black-headed ibis': 1...","{'bird': 63, 'bad': 1, 'bird with very long be...",0.564051,0.000000,0.322757,0.900000
24,2397143,436817,singleton_obj,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'desk': 22, 'filing cabinet': 1, 'drawers': 1...","{'desk': 25, 'filing cabinet': 1, 'table': 6, ...","{'desk': 47, 'filing cabinet': 2, 'drawers': 1...",1.013641,0.529361,0.995722,1.363636
25,2370214,605402,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'top': 1, 'pancho': 3, 'poncho': 19...","{'poncho': 19, 'top': 1, 'shirt': 3, 'parka': ...","{'man': 3, 'top': 2, 'pancho': 6, 'poncho': 38...",1.636475,1.609002,1.035040,0.857143
26,2390817,1246716,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 3, 'curtain': 27, 'curtains': 1, 'wind...","{'curtain': 29, 'net curtain': 1, 'curtains': ...","{'cat': 6, 'curtain': 56, 'curtains': 2, 'wind...",0.644974,0.468996,0.448864,0.833333
27,2319108,1004620,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'gizelle': 1, 'gazelle': 8, 'ram': 2, 'antelo...","{'gazelle': 6, 'antelope': 13, 'elk': 3, 'deer...","{'gizelle': 1, 'gazelle': 14, 'ram': 2, 'antel...",2.532704,2.263809,2.050265,1.300000
28,2333895,3489083,singleton_category,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sheep': 32, 'lamb': 1}","{'sheep': 36, 'lamb': 2, 'ship': 1, 'goat': 1}","{'sheep': 68, 'lamb': 3, 'ship': 1, 'goat': 1}",0.252531,0.000000,0.297472,1.750000
29,2343599,921837,ambiguous_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'helmet': 27, 'hat': 4, 'white helment': 1, '...","{'helmet': 27, 'hat': 5, 'cap': 1, 'hard hat':...","{'helmet': 54, 'hat': 9, 'white helment': 1, '...",1.046303,0.554778,1.243332,1.111111
30,2391964,484515,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'flamingo': 36, 'crane': 1, 'pink flamingo': ...","{'flamingo': 34, 'bird': 4, 'cow': 1, 'pink fl...","{'flamingo': 70, 'crane': 1, 'pink flamingo': ...",0.517962,0.000000,0.485461,1.400000
31,2349445,874713,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 12, 'bench': 12, 'washing line': 1, 'c...","{'bench': 11, 'cat': 10, 'ship': 1, 'tabby cat...","{'cat': 22, 'bench': 23, 'washing line': 2, 'c...",1.407579,1.000000,1.337778,1.058824
32,2350885,864652,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 22, 'sofas': 1, 'couch': 4, 'picture':...","{'cat': 21, 'sofa': 5, 'calico cat': 1, 'art w...","{'cat': 43, 'sofas': 1, 'couch': 7, 'picture':...",1.155864,0.619382,1.113043,1.333333
33,2356284,1694677,ambiguous_synset,boat.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'boat': 30, 'canoe': 1, 'rowboat': 3, 'row bo...","{'boat': 20, 'row boat': 4, 'humans in a boat'...","{'boat': 50, 'canoe': 6, 'rowboat': 7, 'row bo...",1.365989,0.943421,1.588388,2.333333
34,2363673,763118,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 14, 'seagull': 14, 'birds': 1, 'pigeo...","{'seagull': 11, 'bird': 12, 'pigeon': 7, 'tie'...","{'bird': 26, 'seagull': 25, 'birds': 2, 'pigeo...",1.859706,1.495824,1.848040,1.333333
35,2382025,1331957,singleton_obj,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'plane': 8, 'jet': 13, 'fighter jet': 7, 'air...","{'jet': 14, 'helecopter': 1, 'airplane': 3, 'f...","{'plane': 12, 'jet': 27, 'fighter jet': 18, 'a...",2.143719,1.932552,1.746512,1.400000
36,2346998,894511,singleton_obj,train.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'train': 36, 'bus': 1, 'bullet train': 1, 'tr...","{'train': 36, 'floor': 1, 'high-speed train': ...","{'train': 72, 'bus': 1, 'bullet train': 1, 'tr...",0.000000,0.000000,0.000000,0.857143
37,2379445,552755,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,{'zebra': 33},"{'zebra': 24, 'cheeta': 1, 'man': 1, 'ostrich'...","{'zebra': 57, 'cheeta': 1, 'man': 1, 'ostrich'...",0.000000,0.000000,0.000000,2.333333
38,2341107,3656954,singleton_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'hat': 35, 'brim of a hat': 1, 'fisherman's h...","{'hat': 34, 'face': 1, 'hst': 1, 'fishing hat'...","{'hat': 69, 'brim of a hat': 1, 'fisherman's h...",0.000000,0.000000,0.000000,1.000000
39,2349587,2162340,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'parrot': 31, 'tucan': 1, 'bird': 5, 'macaw': 2}","{'parrot': 25, 'bird': 5, 'macaw': 4, 'bike': ...","{'parrot': 56, 'tucan': 1, 'bird': 10, 'macaw'...",0.976301,0.848198,1.096109,1.500000

In [20]:
error = 0
total = 0
for ix,row in fulldf.iterrows():
    a = []
    b = []
    for name in row['responses_total']:
        a.append(row['responses_a'][name])
        b.append(row['responses_b'][name])
        
    #print(a)
    #print(b)
    #r = spearmanr(np.array(a),np.array(b))
    #print(r[0])
    
    error += np.sum(np.abs((np.array(a) - np.array(b))))
    total += len(a)
    
error/total

1.2663934426229508

In [22]:
fulldf.to_csv("40assignments_results.csv",index=False)

In [23]:
np.mean(fulldf['agr_total'])

1.2750091671857429

In [24]:
np.mean(fulldf['agr_a'])

0.9646796526791052

In [25]:
np.mean(fulldf['agr_b'])

1.154019773767479

In [26]:
from scipy.stats import ttest_rel

In [27]:
ttest_rel(fulldf['agr_total'],fulldf['agr_a'])

Ttest_relResult(statistic=9.0128668329964885, pvalue=4.4586532865321303e-11)

In [28]:
np.mean(fulldf[fulldf['cat'] == 'ambiguous_category']['agr_total'])

1.611126818690861

In [29]:
np.mean(fulldf[fulldf['cat'] == 'singleton_category']['agr_total'])

1.097399921257097

In [30]:
for c in set(list(fulldf['synset'])):
    print(c,np.mean(fulldf[fulldf['synset'] == c]['agr_total']))

boat.n.01 1.3659889742138787
furnishing.n.02 1.194764191609065
ship.n.01 1.5457830510722934
ungulate.n.01 0.997363485614458
horse.n.01 0.6064211304180316
overgarment.n.01 2.026793364272883
headdress.n.01 1.075446657660468
neckwear.n.01 1.7384996943383006
train.n.01 0.0
bird.n.01 1.015314045477072
flower.n.01 0.9857369900484061
car.n.01 1.7460561484082942
aircraft.n.01 1.7446986563020304

In [90]:
spell = SpellChecker()
Lem = WordNetLemmatizer()

In [91]:
def check_spelling(answers):
    d = answers
    misspelled = spell.unknown(d.keys())
    ok = {w:d[w] for w in d.keys() if not w in misspelled}
    #print(misspelled)
    #print(ok)
    
    for mis in misspelled:
        #print("Checking:",mis)
        cands = spell.candidates(mis)
        #print("Cand:",cands)
        corrected = False
        for c in ok:
            if c in cands:
                #print("YAY")
                ok[c] += d[mis]
                corrected = True
                break
        if not corrected:
            ok[mis] = d[mis]
            
    clean_answers = Counter()
    for w in ok:
        lem_w = Lem.lemmatize(w)
        clean_answers[lem_w] += ok[w]
        
    return clean_answers

In [93]:
obj2clean_answers = {objid:check_spelling(obj2answers[objid]['t']) for objid in obj2answers}

In [95]:
fulldf['cleaned_responses'] = [obj2clean_answers[objid] for objid in obj2answers]

In [96]:
fulldf

,vg_img_id,vg_object_id,cat,synset,url,responses_a,responses_b,responses_total,agr_total,agr_a,agr_b,mae_a_b,cleaned_responses
0,2389064,507067,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'ottoman': 25, 'outtoman': 1, 'sofar': 1, 'po...","{'ottomon': 1, 'cushion': 2, 'ottoman': 23, 'o...","{'ottoman': 48, 'outtoman': 1, 'sofar': 1, 'po...",1.148969,0.716726,0.850326,0.916667,"{'ottoman': 56, 'dog': 1, 'bed': 2, 'footrest'..."
1,2316226,1055203,ambiguous_synset,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jet fighter': 2, 'jet': 18, 'aircraft': 1, '...","{'airplane': 7, 'jet': 15, 'fighter jet': 8, '...","{'jet fighter': 3, 'jet': 33, 'aircraft': 1, '...",2.065899,1.794737,2.014719,1.294118,"{'jet': 33, 'aircraft': 1, 'plane': 6, 'airpla..."
2,2398812,1175558,ambiguous_synset,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse head': 6, 'horse': 28, 'horse's head':...","{'horse': 27, 'horse's head': 1, 'horse head':...","{'horse head': 12, 'horse': 55, 'horse's head'...",1.212842,0.672295,1.040852,0.900000,"{'horse': 56, 'face': 1, 'van': 1, 'head': 3, ..."
3,2403052,383993,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby zebra': 1, 'zebra': 37, 'line horse': 1}","{'zebra': 36, 'baby zebra': 2, 'horse': 1, 'ch...","{'baby zebra': 3, 'zebra': 73, 'line horse': 1...",0.239874,0.000000,0.297472,1.000000,"{'zebra': 73, 'horse': 1, 'line horse': 1, 'ba..."
4,2393917,1215702,singleton_category,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sunflower': 29, 'sun flower': 4, 'flower': 5...","{'sunflower': 30, 'sun flower': 2, 'tie': 1, '...","{'sunflower': 59, 'sun flower': 6, 'flower': 9...",1.075361,1.024478,0.803072,1.000000,"{'sunflower': 68, 'flower': 10, 'tie': 1}"
5,2363125,2056940,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'man': 1, 'coat': 2, 'shirt': 1...","{'jacket': 16, 'coat': 4, 'upper body of human...","{'jacket': 38, 'man': 2, 'coat': 6, 'shirt': 1...",1.443496,0.871096,1.251629,1.222222,"{'jacket': 39, 'man': 2, 'coat': 6, 'shirt': 1..."
6,2356851,3120857,singleton_obj,flower.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'dandelion': 6, 'flower': 26, 'marigold': 1, ...","{'flower': 27, 'flowers': 1, 'yellow flower': ...","{'dandelion': 11, 'flower': 53, 'marigold': 1,...",0.896113,0.978016,0.625262,1.000000,"{'dandelion': 11, 'flower': 55, 'marigold': 1,..."
7,2405320,654642,ambiguous_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'baby sling': 2, 'towel': 1, 'napki...","{'scarf': 2, 'body wrap': 2, 'carrier': 1, 'up...","{'man': 4, 'baby sling': 4, 'towel': 1, 'napki...",3.357052,3.083587,2.789866,1.093750,"{'man': 4, 'towel': 1, 'napkin': 4, 'hand': 3,..."
8,2393669,1217850,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'car': 35, 'automobile': 1, 'vehicle': 2, 'ca...","{'car': 33, 'salon car': 1, 'automobile': 4, '...","{'car': 68, 'automobile': 5, 'vehicle': 3, 'ca...",0.585927,0.303375,0.494183,1.500000,"{'car': 69, 'automobile': 5, 'vehicle': 3, 'sh..."
9,2330865,2895016,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'dirt bike': 1, 'mat': 15, 'floor mat': 4, 'c...","{'mat': 14, 'floor mat': 9, 'floor matt': 1, '...","{'dirt bike': 1, 'mat': 29, 'floor mat': 13, '...",2.216130,1.750632,1.954940,1.315789,"{'mat': 29, 'carpet': 2, 'motorcycle': 5, 'bik..."
10,2417401,2805653,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bull': 16, 'cow': 12, 'oxen': 2, 'ox pulling...","{'cow': 16, 'animal': 3, 'bull': 9, 'bison': 1...","{'bull': 25, 'cow': 28, 'oxen': 4, 'ox pulling...",1.961709,1.530639,1.597417,1.500000,"{'bull': 25, 'cow': 28, 'ox': 5, 'caribou': 2,..."
11,2362871,2391867,ambiguous_category,ship.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'ferry': 4, 'ship': 16, 'boat': 13, 'yaht': 1...","{'ship': 16, 'boat': 16, 'ferry': 4, 'passenge...","{'ferry': 8, 'ship': 32, 'boat': 29, 'yaht': 1...",1.545783,1.404827,1.392147,0.909091,"{'ferry': 8, 'ship': 32, 'boat': 29, 'yacht': ..."
12,2385325,1298357,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'sofa': 12, 'couch': 21, 'sofar': 1, 'settee'...","{'couch': 22, 'sofa': 14, 'small couch': 1, 'c...","{'sofa': 26, 'couch': 43, 'sofar': 2, 'settee'...",1.113961,0.945660,0.964079,1.000000,"{'sofa': 29, 'couch': 43, 'settee': 1, 'coach'..."
13,2403323,354473,singleton_obj,horse.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'horse': 35, 'clydsdale': 1, 'horus': 1, 'cly...","{'horse': 38, 'clydesdale': 1, 'draft horse': 1}","{'horse': 73, 'clydsdale': 1, 'horus': 1, 'cly...",0.000000,0.000000,0.000000,1.333333,"{'horse': 73, 'horus': 1, 'clydesdale': 2, 'dr..."
14,2367161,2481329,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 22, 'necktie': 5, 'fabric': 1, 'neck t...","{'tie': 20, 'ties': 5, 'necktie': 6, 'neck tie...","{'tie': 42, 'necktie': 11, 'fabric': 2, 'neck ...",1.587083,1.360249,1.291036,1.250000,"{'tie': 49, 'necktie': 17, 'fabric': 2, 'dai':..."
15,2408164,266906,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'penguin': 25, 'bird': 9, 'baby penguin': 1, ...","{'bird': 18, 'penguin': 20, 'penquin': 2}","{'penguin': 45, 'bird': 27, 'baby penguin': 1,...",1.158549,0.833765,1.234498,3.000000,"{'penguin': 48, 'bird': 27, 'bad': 1, 'pigeon'..."
16,4070,1556532,ambiguous_synset,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'carpet': 27, 'bed skirt': 1, 'floor': 4, 'ru...","{'carpet': 24, 'floor': 5, 'rug': 2, 'floor ca...","{'carpet': 51, 'bed skirt': 1, 'floor': 9, 'ru...",0.856996,0.554778,0.965527,1.250000,"{'carpet': 51, 'floor': 9, 'rug': 3, 'flat': 1..."
17,2384721,1305893,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'jacket': 22, 'rain jacket': 1, 'man': 4, 've...","{'person': 3, 'man': 3, 'windbreaker': 2, 'car...","{'jacket': 39, 'rain jacket': 1, 'man': 7, 've...",1.670151,0.619382,2.018821,1.562500,"{'jacket': 39, 'man': 7, 'vest': 1, 'raincoat'..."
18,2327756,2739137,singleton_obj,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'beanie': 4, 'face': 11, 'man': 6, 'touque': ...","{'head': 1, 'face': 13, 'beanie': 6, 'cap': 2,...","{'beanie': 10, 'face': 24, 'man': 10, 'touque'...",2.180037,1.896687,2.079188,1.428571,"{'face': 24, 'man': 10, 'hat': 16, 'men': 1, '..."
19,2373806,1986195,ambiguous_synset,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'police officer': 4, 'police': 2, 'man': 1, '...","{'motorbike': 1, 'man': 3, 'man on scooter': 1...","{'police officer': 5, 'police': 3, 'man': 4, '...",3.131673,2.696620,2.458875,1.250000,"{'police': 4, 'man': 4, 'car': 11, 'scooter': ..."
20,2365594,2254805,singleton_category,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'baby': 3, 'balloon': 12, 'newborn': 1, 'peop...","{'balloon': 17, 'baby': 2, 'man': 3, 'wall dec...","{'baby': 5, 'balloon': 29, 'newborn': 1, 'peop...",1.024478,0.721928,0.993897,1.454545,"{'baby': 5, 'balloon': 30, 'newborn': 1, 'peop..."
21,2316079,3206535,ambiguous_synset,neckwear.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'tie': 1, 'bowtie': 12, 'bow tie': 8, 'bow': ...","{'bowtie': 15, 'bow': 8, 'bow tie': 8, 'knot':...","{'tie': 3, 'bowtie': 27, 'bow tie': 16, 'bow':...",1.889917,1.565596,1.969187,1.230769,"{'tie': 3, 'bow': 19, 'hairband': 1, 'knot': 1..."
22,2417043,3198072,ambiguous_category,car.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'van': 16, 'bus': 14, 'minibus': 1, 'tour-bus...","{'van': 13, 'bus': 20, 'vehicle': 1, 'automobi...","{'van': 29, 'bus': 34, 'minibus': 1, 'tour-bus...",1.520568,0.996792,1.465013,1.700000,"{'van': 29, 'bus': 34, 'minibus': 1, 'automobi..."
23,2370234,1757900,singleton_category,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 31, 'bad': 1, 'bird with very long be...","{'bird': 32, 'swan': 1, 'black-headed ibis': 1...","{'bird': 63, 'bad': 1, 'bird with very long be...",0.564051,0.000000,0.322757,0.900000,"{'bird': 63, 'bad': 1, 'pelican': 2, 'ibis': 2..."
24,2397143,436817,singleton_obj,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'desk': 22, 'filing cabinet': 1, 'drawers': 1...","{'desk': 25, 'filing cabinet': 1, 'table': 6, ...","{'desk': 47, 'filing cabinet': 2, 'drawers': 1...",1.013641,0.529361,0.995722,1.363636,"{'desk': 47, 'drawer': 1, 'table': 9, 'cabinet..."
25,2370214,605402,singleton_category,overgarment.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'man': 2, 'top': 1, 'pancho': 3, 'poncho': 19...","{'poncho': 19, 'top': 1, 'shirt': 3, 'parka': ...","{'man': 3, 'top': 2, 'pancho': 6, 'poncho': 38...",1.636475,1.609002,1.035040,0.857143,"{'man': 3, 'top': 2, 'pancho': 6, 'poncho': 38..."
26,2390817,1246716,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 3, 'curtain': 27, 'curtains': 1, 'wind...","{'curtain': 29, 'net curtain': 1, 'curtains': ...","{'cat': 6, 'curtain': 56, 'curtains': 2, 'wind...",0.644974,0.468996,0.448864,0.833333,"{'cat': 6, 'curtain': 58, 'window': 1, 'net cu..."
27,2319108,1004620,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'gizelle': 1, 'gazelle': 8, 'ram': 2, 'antelo...","{'gazelle': 6, 'antelope': 13, 'elk': 3, 'deer...","{'gizelle': 1, 'gazelle': 14, 'ram': 2, 'antel...",2.532704,2.263809,2.050265,1.300000,"{'gazelle': 16, 'ram': 2, 'antelope': 24, 'elk..."
28,2333895,3489083,singleton_category,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'sheep': 32, 'lamb': 1}","{'sheep': 36, 'lamb': 2, 'ship': 1, 'goat': 1}","{'sheep': 68, 'lamb': 3, 'ship': 1, 'goat': 1}",0.252531,0.000000,0.297472,1.750000,"{'sheep': 68, 'lamb': 3, 'ship': 1, 'goat': 1}"
29,2343599,921837,ambiguous_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'helmet': 27, 'hat': 4, 'white helment': 1, '...","{'helmet': 27, 'hat': 5, 'cap': 1, 'hard hat':...","{'helmet': 54, 'hat': 9, 'white helment': 1, '...",1.046303,0.554778,1.243332,1.111111,"{'helmet': 55, 'hat': 9, 'cap': 1, 'hardhat': ..."
30,2391964,484515,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'flamingo': 36, 'crane': 1, 'pink flamingo': ...","{'flamingo': 34, 'bird': 4, 'cow': 1, 'pink fl...","{'flamingo': 70, 'crane': 1, 'pink flamingo': ...",0.517962,0.000000,0.485461,1.400000,"{'flamingo': 70, 'crane': 1, 'bird': 5, 'cow':..."
31,2349445,874713,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 12, 'bench': 12, 'washing line': 1, 'c...","{'bench': 11, 'cat': 10, 'ship': 1, 'tabby cat...","{'cat': 22, 'bench': 23, 'washing line': 2, 'c...",1.407579,1.000000,1.337778,1.058824,"{'cat': 22, 'bench': 23, 'rail': 1, 'ship': 1,..."
32,2350885,864652,singleton_category,furnishing.n.02,http://www.coli.uni-saarland.de/~carina/object...,"{'cat': 22, 'sofas': 1, 'couch': 4, 'picture':...","{'cat': 21, 'sofa': 5, 'calico cat': 1, 'art w...","{'cat': 43, 'sofas': 1, 'couch': 7, 'picture':...",1.155864,0.619382,1.113043,1.333333,"{'cat': 43, 'sofa': 6, 'couch': 7, 'picture': ..."
33,2356284,1694677,ambiguous_synset,boat.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'boat': 30, 'canoe': 1, 'rowboat': 3, 'row bo...","{'boat': 20, 'row boat': 4, 'humans in a boat'...","{'boat': 50, 'canoe': 6, 'rowboat': 7, 'row bo...",1.365989,0.943421,1.588388,2.333333,"{'boat': 50, 'canoe': 6, 'horse': 1, 'ship': 1..."
34,2363673,763118,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'bird': 14, 'seagull': 14, 'birds': 1, 'pigeo...","{'seagull': 11, 'bird': 12, 'pigeon': 7, 'tie'...","{'bird': 26, 'seagull': 25, 'birds': 2, 'pigeo...",1.859706,1.495824,1.848040,1.333333,"{'bird': 28, 'seagull': 28, 'pigeon': 14, 'gul..."
35,2382025,1331957,singleton_obj,aircraft.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'plane': 8, 'jet': 13, 'fighter jet': 7, 'air...","{'jet': 14, 'helecopter': 1, 'airplane': 3, 'f...","{'plane': 12, 'jet': 27, 'fighter jet': 18, 'a...",2.143719,1.932552,1.746512,1.400000,"{'plane': 12, 'jet': 27, 'airplane': 9, 'aircr..."
36,2346998,894511,singleton_obj,train.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'train': 36, 'bus': 1, 'bullet train': 1, 'tr...","{'train': 36, 'floor': 1, 'high-speed train': ...","{'train': 72, 'bus': 1, 'bullet train': 1, 'tr...",0.000000,0.000000,0.000000,0.857143,"{'train': 72, 'bus': 1, 'tram': 1, 'floor': 1,..."
37,2379445,552755,ambiguous_synset,ungulate.n.01,http://www.coli.uni-saarland.de/~carina/object...,{'zebra': 33},"{'zebra': 24, 'cheeta': 1, 'man': 1, 'ostrich'...","{'zebra': 57, 'cheeta': 1, 'man': 1, 'ostrich'...",0.000000,0.000000,0.000000,2.333333,"{'zebra': 57, 'man': 1, 'ostrich': 1, 'stripe'..."
38,2341107,3656954,singleton_category,headdress.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'hat': 35, 'brim of a hat': 1, 'fisherman's h...","{'hat': 34, 'face': 1, 'hst': 1, 'fishing hat'...","{'hat': 69, 'brim of a hat': 1, 'fisherman's h...",0.000000,0.000000,0.000000,1.000000,"{'hat': 69, 'face': 1, 'hst': 1, 'brim': 1, 'f..."
39,2349587,2162340,ambiguous_synset,bird.n.01,http://www.coli.uni-saarland.de/~carina/object...,"{'parrot': 31, 'tucan': 1, 'bird': 5, 'macaw': 2}","{'parrot': 25, 'bird': 5, 'macaw': 4, 'bike': ...","{'parrot': 56, 'tucan': 1, 'bird': 10, 'macaw'...",0.976301,0.848198,1.096109,1.500000,"{'parrot': 57, 'bird': 10, 'macaw': 7, 'bike':..."

In [97]:
fulldf['agr_cleaned'] = fulldf['cleaned_responses'].apply(lambda x: get_agreement(x))

In [47]:
for c in set(list(fulldf['synset'])):
    print(c,np.mean(fulldf[fulldf['synset'] == c]['agr_total']))

2

In [98]:
np.mean(fulldf['agr_cleaned'])

1.2491225067869518

In [99]:
np.mean(fulldf['agr_total'])

1.2750091671857429

In [82]:
spell.known(spell.edit_distance_2('pouf'))

{'aoun',
 'auf',
 'boeuf',
 'bou',
 'bout',
 'buf',
 'chouf',
 'coif',
 'cou',
 'coum',
 'coun',
 'coup',
 'cour',
 'cous',
 'diouf',
 'doff',
 'domf',
 'dorf',
 'doug',
 'dour',
 'fou',
 'foul',
 'four',
 'goff',
 'golf',
 'goof',
 'gout',
 'hof',
 'hoff',
 'hoof',
 'hou',
 'hour',
 'hous',
 'iou',
 'ious',
 'jour',
 'loaf',
 'lou',
 'loud',
 'lout',
 'moue',
 'neuf',
 'norf',
 'nou',
 'noun',
 'nour',
 'nous',
 'oaf',
 'of',
 'off',
 'olf',
 'omf',
 'opus',
 'orf',
 'osf',
 'ou',
 'oui',
 'oup',
 'our',
 'out',
 'paf',
 'pau',
 'paul',
 'pcf',
 'pdf',
 'pdgf',
 'peu',
 'peut',
 'peux',
 'pf',
 'pff',
 'phu',
 'piaf',
 'pious',
 'pius',
 'plf',
 'plug',
 'plum',
 'plus',
 'plut',
 'pmsf',
 'pnsf',
 'po',
 'poa',
 'poc',
 'pod',
 'pods',
 'poe',
 'poem',
 'poet',
 'pogo',
 'pohl',
 'poi',
 'pois',
 'poke',
 'poky',
 'pol',
 'pole',
 'poli',
 'poll',
 'polo',
 'poly',
 'pom',
 'pomp',
 'poms',
 'pon',
 'pond',
 'pong',
 'pons',
 'pont',
 'pony',
 'poo',
 'poof',
 'poofs',
 'pooh',
 'pook',
 'pool',
 'poop',
 'poor',
 'poos',
 'pop',
 'pope',
 'pops',
 'por',
 'pore',
 'pork',
 'porn',
 'port',
 'porua',
 'porz',
 'pos',
 'pos.',
 'posc',
 'pose',
 'posh',
 'posi',
 'poss',
 'post',
 'posy',
 'pot',
 'pots',
 'pott',
 'pou',
 'pouch',
 'pouffe',
 'poul',
 'poum',
 'pound',
 'pour',
 'pours',
 'pout',
 'pouts',
 'pow',
 'pows',
 'pox',
 'poxy',
 'ppu',
 'prof',
 'proof',
 'proud',
 'prout',
 'pru',
 'prue',
 'psu',
 'pu',
 'pub',
 'pud',
 'puff',
 'pug',
 'puk',
 'pun',
 'pup',
 'pur',
 'pus',
 'put',
 'puy',
 'pvu',
 'rauf',
 'rolf',
 'roof',
 'rou',
 'rous',
 'rout',
 'roux',
 'sou',
 'souk',
 'soul',
 'soup',
 'sour',
 'sous',
 'spoof',
 'spout',
 'tof',
 'toff',
 'tofu',
 'tour',
 'tous',
 'tout',
 'uf',
 'vous',
 'wolf',
 'woof',
 'wou',
 'woul',
 'yoof',
 'you',
 "you'",
 'your',
 'yous',
 'zoff',
 'zou'}

In [81]:
spell.edit_distance_2['pouffe']

15

In [103]:
for c in set(list(fulldf['synset'])):
    print(c,"%.3f"%np.mean(fulldf[fulldf['synset'] == c]['agr_total']))

boat.n.01 1.366
furnishing.n.02 1.195
ship.n.01 1.546
ungulate.n.01 0.997
horse.n.01 0.606
overgarment.n.01 2.027
headdress.n.01 1.075
neckwear.n.01 1.738
train.n.01 0.000
bird.n.01 1.015
flower.n.01 0.986
car.n.01 1.746
aircraft.n.01 1.745

In [105]:
np.mean(fulldf['agr_total'])

1.2750091671857429

In [89]:
Lem.lemmatize('fighter jet (airplane)')

'fighter jet (airplane)'

In [110]:
for d in fulldf[fulldf['synset'] == 'train.n.01']['responses_total']:
    print(d)

Counter({'train': 72, 'bus': 1, 'bullet train': 1, 'tram': 1, 'floor': 1, 'high-speed train': 1, 'fast train': 1})